#!/bin/bash
#
# Restores the latest Ganglia RRD archives present. Assumes
# the gmetad service is not running (should be started before gmetad).
#
# chkconfig: 2345 19 81
# description: Ganglia RRD restore
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		         version 6.2 (SideWinder)
# 		         version 7.0 (Manzanita)
# 
# Copyright (c) 2000 - 2017 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
# $Log: ganglia-restore-rrds,v $
# Revision 1.10  2012/11/27 00:48:57  phil
# Copyright Storm for Emerald Boa
#
# Revision 1.9  2012/05/06 05:49:06  phil
# Copyright Storm for Mamba
#
# Revision 1.8  2011/07/23 02:30:59  phil
# Viper Copyright
#
# Revision 1.7  2010/09/07 23:53:14  bruno
# star power for gb
#
# Revision 1.6  2009/10/30 22:46:02  bruno
# need to touch the file '/var/lock/subsys/ganglia-restore-rrds', otherwise
# this init script will *not* be called on shutdown
#
# Revision 1.5  2009/05/01 19:07:16  mjk
# chimi con queso
#
# Revision 1.4  2008/10/18 00:56:08  mjk
# copyright 5.1
#
# Revision 1.3  2008/03/06 23:41:51  mjk
# copyright storm on
#
# Revision 1.2  2007/06/23 04:03:35  mjk
# mars hill copyright
#
# Revision 1.1  2006/11/30 01:15:31  bruno
# moved ganglia-restore-rrds into the base roll
#
# also configured the service to be enabled on boot
#
# Revision 1.6  2006/09/11 22:47:05  mjk
# monkey face copyright
#
# Revision 1.5  2006/08/10 00:09:28  mjk
# 4.2 copyright
#
# Revision 1.4  2005/10/12 18:08:35  mjk
# final copyright for 4.1
#
# Revision 1.3  2005/09/16 01:02:15  mjk
# updated copyright
#
# Revision 1.2  2005/05/24 21:21:50  mjk
# update copyright, release is not any closer
#
# Revision 1.1  2005/03/01 02:02:44  mjk
# moved from core to base
#
# Revision 1.6  2004/03/25 03:15:30  bruno
# touch 'em all!
#
# update version numbers to 3.2.0 and update copyrights
#
# Revision 1.5  2004/02/12 20:27:12  fds
# Saves rrds on shutdown as suggested by Thomas Linden
#
# Revision 1.4  2003/10/17 18:58:10  fds
# Dont paint the town red.
#
# Revision 1.3  2003/08/15 22:34:46  mjk
# 3.0.0 copyright
#
# Revision 1.2  2003/08/06 00:06:13  fds
# Safer
#
# Revision 1.1  2003/07/23 21:28:20  fds
# Initial design
#
# Revision 1.1  2003/07/23 19:15:16  fds
# First design
#
#

# set ganglia-restore-rrd stop before $local_fs stop
### BEGIN INIT INFO
# Provides: ganglia-restore-rrd
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Ganglia RRDs restore
### END INIT INFO

archives=/var/lib/ganglia/archives

case "$1" in
	start)
		echo -n "Restoring Ganglia RRDs..."
		touch /var/lock/subsys/ganglia-restore-rrds
		echo

		# Check that the rrd archives directory exists
		[ -d $archives ] || exit 0

		# Choose the most recent archives.
		# Assumes that only archivess are in this directory.
		useme=`ls -t $archives | head -1`

		# Punt if we don't find anything.
		[[ $useme == "" ]] && exit 0

		# Restore the RRDs.
		tar xf $archives/$useme
		;;
	stop)
		$0 save
		rm -f /var/lock/subsys/ganglia-restore-rrds
		;;
	save)
		echo -n "Saving Ganglia RRD metric histories..."
		/etc/cron.weekly/ganglia-save-rrds.cron
		echo
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		echo "Available Ganglia RRD metric history archives:"
		ls $archives
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|status}"
		exit 1
esac

exit 0
